/* Generated by Yosys 0.20+1 (git sha1 60a787fa500, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_sqd_1010(din, reset, clk, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  input clk;
  wire clk;
  wire [3:0] cst;
  input din;
  wire din;
  input reset;
  wire reset;
  output y;
  wire y;
  sky130_fd_sc_hd__clkinv_1 _09_ (
    .A(cst[1]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2b_1 _10_ (
    .A_N(reset),
    .B(din),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _11_ (
    .A(cst[0]),
    .B(cst[3]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nor3_1 _12_ (
    .A(cst[1]),
    .B(reset),
    .C(din),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _13_ (
    .A1_N(cst[2]),
    .A2_N(_06_),
    .B1(_07_),
    .B2(_08_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor2b_1 _14_ (
    .A(din),
    .B_N(cst[3]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor3b_1 _15_ (
    .A(reset),
    .B(din),
    .C_N(cst[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _16_ (
    .A(_05_),
    .B(_06_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _17_ (
    .A(_06_),
    .B(_07_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_04_),
    .Q(cst[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_01_),
    .Q(cst[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(_02_),
    .Q(cst[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(_03_),
    .Q(cst[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _22_ (
    .CLK(clk),
    .D(_00_),
    .Q(y)
  );
endmodule
